# Generated by Django 3.2.9 on 2021-11-19 17:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default=None, null=True)),
                ('ingredients', models.TextField()),
                ('is_veggie', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_day', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shopping_list', models.TextField(default=None, null=True)),
                ('fri_din', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu12', to='api.dish')),
                ('fri_lun', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu5', to='api.dish')),
                ('mon_din', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu8', to='api.dish')),
                ('mon_lun', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu1', to='api.dish')),
                ('sat_din', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu13', to='api.dish')),
                ('sat_lun', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu6', to='api.dish')),
                ('sun_din', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu14', to='api.dish')),
                ('sun_lun', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu7', to='api.dish')),
                ('thu_din', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu11', to='api.dish')),
                ('thu_lun', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu4', to='api.dish')),
                ('tue_din', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu9', to='api.dish')),
                ('tue_lun', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu2', to='api.dish')),
                ('wed_din', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu10', to='api.dish')),
                ('wed_lun', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu3', to='api.dish')),
            ],
        ),
    ]
