# Generated by Django 3.2.9 on 2021-11-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('lastname', models.CharField(default=None, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('verified', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
